name: detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "install detekt"
         run: curl -sSLO https://github.com/detekt/detekt/releases/download/v1.13.1/detekt && chmod a+x detekt
       
       - name: "run detekt"
         run: ./detekt --config detekt.yml --fail-fast --build-upon-default-config
