name: detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "install detekt"
         uses: yarn add detekt
       
       - name: "run detekt"
         uses: detekt
         with:
          args: --fail-fast --config detekt.yml
