name: detekt

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
   detekt:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "install detekt"
         run: yarn add detekt
       
       - name: "run detekt"
         run: yarn detekt --config detekt.yml --fail-fast --build-upon-default-config
