# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Install Danger
        run: yarn add danger danger-plugin-lint-report@1.0.0
      
      - name: Run KtLint
        run: ./gradlew lintKotlin
        continue-on-error: true

      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true

      - name: Run Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
