name: Lint

on: push

jobs:

  lint:
      name: Lint code base

      runs-on: ubuntu-latest

      steps:

        - name: Checkout code
          uses: actions/checkout@v2

        - name: Run KtLint
          run: ./gradlew lintKotlin
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: Run Detekt
          run: ./gradlew detekt
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}