# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Install Danger
        run: yarn add danger danger-plugin-lint-report@1.0.0
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run KtLint
        run: ./gradlew lintKotlin
        continue-on-error: true
      - name: Run Detekt
        run: ./gradlew detekt
        continue-on-error: true
      - name: Run Android Lint
        run: ./gradlew lintDebug
        continue-on-error: true
      - name: Run Danger
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
